INSERT INTO tblinSpireSalesDataHistoryACCORD_CPWTrial
SELECT *, NULL, NULL FROM tblinSpireSalesDataHistoryACCORD
WHERE Department IN ('Customer Retention') 
AND OrderDate BETWEEN '01-01-2011' AND '02-28-2011'

UPDATE tblinSpireSalesDataHistoryACCORD_CPWTrial
SET InitialDealerCode = B.Connection_Channel
FROM tblinSpireSalesDataHistoryACCORD_CPWTrial A JOIN MIReporting.dbo.rep_000805_Current B
ON A.CTN = B.Subscriber_CTN


UPDATE tblinSpireSalesDataHistoryACCORD_CPWTrial
SET InitialDealerCode = LTRIM(RTRIM(InitialDealerCode))

UPDATE tblinSpireSalesDataHistoryACCORD_CPWTrial
SET CPWFlag = 'CPW Connection'
WHERE InitialDealerCode IN
('10100000',
'10100001',
'10100002',
'10100007',
'10100009',
'10100011',
'10100012',
'10100015',
'10100100',
'83600000',
'83600001',
'83600002',
'83600003',
'83600004',
'83600006',
'83600007',
'83600009',
'CP900000', 
'CP900001', 
'VA600000')  

UPDATE tblinSpireSalesDataHistoryACCORD_CPWTrial
SET CPWFlag = 'Non CPW Connection'
WHERE CPWFlag IS NULL

SELECT 
OrderDate,
OrderWeek,
OrderMonth,
Agent,Team,
CCM,
Site,
Department,
RFunction,
Channel,
BusinessUnit,
Network,
Segment,
OrderType,
AccordFlag,
CPWFlag,
SUM(ContractGrossVolume),
SUM(CASE WHEN AccordFlag = 'Accord' THEN ContractGrossVolume ELSE 0 END),
SUM(ContractNetVolume),
SUM(ShortTermExtensions),
SUM(ContractGrossPeriod),
SUM(ContractNetPeriod),
SUM(SIMOnlyVolume),
SUM(ContractSIMOnly),
SUM(MaintenanceOrders),
ContractPeriodSummary,
SUM(HandsetVolume),
SUM(HandsetCosts),
SUM(HandsetSubsidy),
SUM(HandsetRevenue),
SUM(DatacardVolume),
SUM(DatacardCosts),
SUM(DatacardSubsidy),
SUM(DatacardRevenue),
SUM(NetbookVolume),
SUM(NetbookCosts),
SUM(NetbookSubsidy),
SUM(NetbookRevenue),
SUM(HandsetExchanges),
SUM(HandsetExchangeCost),
SUM(AccessoryVolume),
SUM(AccessoryCost),
SUM(AccessoryRevenue),
SUM(DeliveryVolume),
SUM(DeliveryCost),
SUM(DeliveryRevenue),
SUM(CreditNoteVolume),
SUM(CreditNoteCost),
SUM(PricePlanChanges),
SUM(PricePlanSTCT),
SUM(PricePlanRecCommCost),
SUM(PricePlanFixCommCost),
SUM(Services),
SUM(ServicesRecCommCost),
SUM(ServicesFixCommCost),
SUM(Discounts),
SUM(DiscountPeriod),
SUM(DiscountCosts),
SUM(PricePlanLineRental),
SUM(GPNotionalProfit),
SUM(NPNotionalProfit),
SUM(Service1Volume),
SUM(Service1BundledVolume),
SUM(Service1Profit),
SUM(Service2Volume),
SUM(Service2BundledVolume),
SUM(Service2Profit),
SUM(Service3Volume),
SUM(Service3BundledVolume),
SUM(Service3Profit),
SUM(Service4Volume),
SUM(Service4BundledVolume),
SUM(Service4Profit),
SUM(Service5Volume),
SUM(Service5BundledVolume),
SUM(Service5Profit),
SUM(Service6Volume),
SUM(Service6BundledVolume),
SUM(Service6Profit),
SUM(Service7Volume),
SUM(Service7BundledVolume),
SUM(Service7Profit),
SUM(Service8Volume),
SUM(Service8BundledVolume),
SUM(Service8Profit),
SUM(Service9Volume),
SUM(Service9BundledVolume),
SUM(Service9Profit),
SUM(Service10Volume),
SUM(Service10BundledVolume),
SUM(Service10Profit),
SUM(RIV),
SUM(DefaultRIV),
SUM(AccordMaxBudget),
SUM(AccordTargetBudget)
FROM tblinSpireSalesDataHistoryACCORD_CPWTrial
GROUP BY 
OrderDate,
OrderWeek,
OrderMonth,
Agent,
Team,
CCM,
Site,
Department,
RFunction,
Channel,
BusinessUnit,
Network,
Segment,
OrderType,
ContractPeriodSummary,
AccordFlag,
CPWFlag