--CREATE PROCEDURE spInSpireCopyOver AS

CREATE TABLE #tblinSpireSalesDataHistory (
	[OrderNumber] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[OrderDate] [datetime] NULL ,
	[OrderWeek] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[OrderMonth] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[CTN] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[BAN] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[AgentID] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[Agent] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[Team] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[CCM] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[Site] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[Department] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[RFunction] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[Channel] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[BusinessUnit] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[Network] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[Segment] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[Campaign] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[OrderType] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[TariffGroup] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[SubscriberStatus] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[HandsetDescription] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[PricePlanDescription] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[PricePlanSOC] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[ContractGrossVolume] [int] NULL ,
	[ContractNetVolume] [int] NULL ,
	[ShortTermExtensions] [int] NULL ,
	[ContractGrossPeriod] [int] NULL ,
	[ContractNetPeriod] [int] NULL ,
	[SIMOnlyVolume] [int] NULL ,
	[ContractSIMOnly] [int] NULL ,
	[MaintenanceOrders] [int] NULL ,
	[ContractPeriodSummary] [int] NULL ,
	[HandsetVolume] [int] NULL ,
	[HandsetCosts] [money] NULL ,
	[HandsetSubsidy] [money] NULL ,
	[HandsetRevenue] [money] NULL ,
	[DatacardVolume] [int] NULL ,
	[DatacardCosts] [money] NULL ,
	[DatacardSubsidy] [money] NULL ,
	[DatacardRevenue] [money] NULL ,
	[NetbookVolume] [int] NULL ,
	[NetbookCosts] [money] NULL ,
	[NetbookSubsidy] [money] NULL ,
	[NetbookRevenue] [money] NULL ,
	[HandsetExchanges] [int] NULL ,
	[HandsetExchangeCost] [money] NULL ,
	[AccessoryVolume] [int] NULL ,
	[AccessoryCost] [money] NULL ,
	[AccessoryRevenue] [money] NULL ,
	[DeliveryVolume] [int] NULL ,
	[DeliveryCost] [money] NULL ,
	[DeliveryRevenue] [money] NULL ,
	[CreditNoteVolume] [int] NULL ,
	[CreditNoteCost] [money] NULL ,
	[PricePlanChanges] [int] NULL ,
	[PricePlanSTCT] [int] NULL ,
	[PricePlanRecCommCost] [money] NULL ,
	[PricePlanFixCommCost] [money] NULL ,
	[Services] [int] NULL ,
	[ServicesRecCommCost] [money] NULL ,
	[ServicesFixCommCost] [money] NULL ,
	[Discounts] [int] NULL ,
	[DiscountPeriod] [int] NULL ,
	[DiscountCosts] [money] NULL ,
	[PricePlanLineRental] [money] NULL ,
	[GPNotionalProfit] [money] NULL ,
	[NPNotionalProfit] [money] NULL ,
	[Service1Volume] [int] NULL ,
	[Service1BundledVolume] [int] NULL ,
	[Service1Profit] [money] NULL ,
	[Service2Volume] [int] NULL ,
	[Service2BundledVolume] [int] NULL ,
	[Service2Profit] [money] NULL ,
	[Service3Volume] [int] NULL ,
	[Service3BundledVolume] [int] NULL ,
	[Service3Profit] [money] NULL ,
	[Service4Volume] [int] NULL ,
	[Service4BundledVolume] [int] NULL ,
	[Service4Profit] [money] NULL ,
	[Service5Volume] [int] NULL ,
	[Service5BundledVolume] [int] NULL ,
	[Service5Profit] [money] NULL ,
	[Service6Volume] [int] NULL ,
	[Service6BundledVolume] [int] NULL ,
	[Service6Profit] [money] NULL ,
	[Service7Volume] [int] NULL ,
	[Service7BundledVolume] [int] NULL ,
	[Service7Profit] [money] NULL ,
	[Service8Volume] [int] NULL ,
	[Service8BundledVolume] [int] NULL ,
	[Service8Profit] [money] NULL ,
	[Service9Volume] [int] NULL ,
	[Service9BundledVolume] [int] NULL ,
	[Service9Profit] [money] NULL ,
	[Service10Volume] [int] NULL ,
	[Service10BundledVolume] [int] NULL ,
	[Service10Profit] [money] NULL ,
	[RIV] [money] NULL ,
	[DefaultRIV] [money] NULL 
) 





INSERT INTO #tblinSpireSalesDataHistory
SELECT * FROM tblinSpireSalesDataHistory
WHERE OrderDate > Getdate()-60